#!/usr/bin/env python3
# Copyright 2022 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

'''
Prints the declarations for the OpenBSD libc syscall stubs.

The syscall stub functions have formulaic names and instructions.
Hence we look for such names and then disassemble them just in case
to confirm they do in fact contain a 'syscall' instruction. This
makes the check amd64-specific.
'''

import glob
import re
import subprocess


Stubs = dict[str, tuple[int, str]]

def find_stubs(libc_file : str) -> Stubs:
    nm_proc = subprocess.Popen(["/usr/bin/nm", libc_file], stdout=subprocess.PIPE)
    (output, _) = nm_proc.communicate()
    assert 0 == nm_proc.wait()

    thread_stub_re = re.compile('^([0-9a-f]+) T _thread_sys_(\w+)')
    libc_name_re = re.compile('^([0-9a-f]+) t _libc_(\w+)')
    thread_stub_addrs = {}
    libc_stub_addrs = {}
    for line in output.decode("utf-8").splitlines():
        if m := thread_stub_re.match(line):
            thread_stub_addrs[int(m.group(1), 16)] = m.group(2)
        if m := libc_name_re.match(line):
            libc_stub_addrs[int(m.group(1), 16)] = m.group(2)

    return {
        thread_stub_name : (addr, libc_stub_addrs.get(addr))
        for addr, thread_stub_name in thread_stub_addrs.items()
    }


def find_syscall_instrs(libc_file : str, stubs : Stubs) -> dict[str, str]:
    # Checks that all the found stubs have a syscall instruction.
    syscall_inst_re = re.compile('^\s*[0-9a-f]+:.+\s+syscall', flags=re.MULTILINE)
    known_stubs = {}
    for name, (addr, libc_name) in stubs.items():
        objdump_cmd = [
            "/usr/bin/objdump",
            "--disassemble",
            f"--start-address=0x%x" % addr,
            f"--stop-address=0x%x" % (addr + 40),
            libc_file
        ]
        objdump_proc = subprocess.Popen(objdump_cmd, stdout=subprocess.PIPE)
        (output, _) = objdump_proc.communicate()
        assert 0 == objdump_proc.wait()
        out_str = output.decode('utf-8')
        if syscall_inst_re.search(out_str):
            known_stubs[name] = libc_name
        else:
            print(f"The stub for '%s' has unexpected instructions:\n%s" % (name, out_str),
                  file=sys.stderr)
    return known_stubs


def main():
    # Finds the one and only libc, expected to fail if multiple exist.
    (libc_file,) = glob.glob("/usr/lib/libc.so.*")

    libc_stub_addrs = find_stubs(libc_file)

    known_stubs = find_syscall_instrs(libc_file, libc_stub_addrs)

    print ("// AUTOGENERATED FILE, use openbsd_libc_syscall_stubs.py to rebuild.")
    print ("// Generated from", libc_file)
    for stub in sorted(known_stubs):
        print(f"extern void* _thread_sys_%s;" % stub)

main()

